/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SalesTaxes;

import SalesTaxes.products.Product;

public class App {

    public static void main(String[] args) {

        System.out.println("App!");


    }
}
